name: Run unit tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3
        # Setup which version of Python to use
      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Run the tests. I'm using pytest and the file is in the tests directory.
      - name: Run tests
        run: python -m unittest tests/*

